version: '3.8'

services:
  stable-diffusion-webui:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: rukapsan/hotgens:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3001"
    environment:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    restart: unless-stopped